id = "mlir-suite"
name = "MLIR Suite"
description = "MLIR, TableGen, and PDLL with LSP support and smart highlighting."
version = "0.6.0"
schema_version = 1
authors = ["Buyun Xu <xubuyun@outlook.com>"]
repository = "https://github.com/felixtensor/zed-mlir-suite"

[grammars.mlir]
repository = "https://github.com/felixtensor/tree-sitter-mlir"
commit = "d772e1bc7923c77a4ea69831d9ab9d2ae1a22b7b"

[grammars.tablegen]
repository = "https://github.com/felixtensor/tree-sitter-tablegen"
commit = "e803084a70b2d8bb47bfe3c390dc6756e67d9da8"

[grammars.pdll]
repository = "https://github.com/felixtensor/tree-sitter-pdll"
commit = "8ba537e1742bc4f574bd9d6f76c45e91db7791d7"

[language_servers.mlir-lsp-server]
name = "mlir-lsp-server"
languages = ["MLIR"]

[language_servers.mlir-pdll-lsp-server]
name = "mlir-pdll-lsp-server"
languages = ["PDLL"]

[language_servers.tblgen-lsp-server]
name = "tblgen-lsp-server"
languages = ["TableGen"]
